/* Premium executive narrative layer — review branch only. */
(function(){
  const React = window.React;
  const { useMemo } = React;

  const CASES = [
    {num:"01",title:"Strategic Planning, Implementation & Institutional Operating Cycle",domain:"Strategy implementation",mandates:["Strategic planning","Implementation","KPIs","Institutional effectiveness"],summary:"End-to-end strategy work spanning independent closure of the 2014–2019 plan, ownership of the 2025–2030 School of Medicine planning process, stakeholder and workgroup coordination, KPI architecture, implementation monitoring, annual review, and CQI linkage.",evidence:["ev-strat-closure-2014-2019","execstrat-01","ev-strategy-workgroups","ev-strategy-annual-monitoring","ev-allied-health-strategy-data"]},
    {num:"02",title:"Institutional Effectiveness & Enterprise Data Governance",domain:"Institutional effectiveness",mandates:["Data governance","Dashboards","Assessment","Decision support"],summary:"A cross-office evidence architecture connecting 90+ institutional data sources and the learner lifecycle from admissions through practice, supporting accreditation, CQI, strategic-plan monitoring, executive dashboards, data quality, stewardship, and mission accountability.",evidence:["ev-lifecycle-data-architecture","ev-longitudinal-education-db","an-10","ev-faculty-data-governance","ev-education-outcomes"]},
    {num:"03",title:"Accreditation Leadership & Continuous Readiness",domain:"Accreditation",mandates:["LCME","Institutional accreditation","Self-study","Continuous readiness"],summary:"Accreditation leadership across LCME, ACGME, ACCME, SACSCOC data-response support, ACS education-institute accreditation, and emerging accreditation policy—grounded in evidence development, self-study support, standards interpretation, site-visit readiness, reporting, response, and continuous monitoring.",evidence:["cqi-01","ev-lcme-dci-selfstudy","ev-accme","ev-sacscoc","ev-acs-aei","ev-cphe","ev-lcme-steering"]},
    {num:"04",title:"Predictive Accreditation Risk, CQI & Corrective Action",domain:"Regulatory risk & CQI",mandates:["Risk surveillance","CQI","Corrective action","Site readiness"],summary:"Moves accreditation upstream from retrospective compliance to predictive surveillance by integrating Annual Institutional Review, program evaluation, surveys, citations and outcomes to identify elevated ACGME risk, likely citation domains, and targeted pre-review corrective actions.",evidence:["ev-acgme-predictive","ev-acgme-air","ev-acgme-ape-surveys","ev-acgme-corrective-action","ev-acgme-cler-umcno"]},
    {num:"05",title:"Cross-Functional Governance & Matrix Leadership",domain:"Organizational leadership",mandates:["Matrix leadership","Governance","Facilitation","Shared accountability"],summary:"Leadership through process ownership, evidence authority, committee governance, executive advising, and cross-functional coordination rather than direct-line supervision—spanning Dean’s Staff, strategic planning, LCME, CME, MCIP, GME and health-system partnership forums.",evidence:["ev-dean-staff-governance","ev-strategy-workgroups","ev-lcme-steering","ev-cme-committee","ev-mcip-informatics-team","ev-umcno-academic-advisory"]},
    {num:"06",title:"Academic Health-System Enterprise Integration",domain:"Enterprise partnerships",mandates:["Enterprise integration","Clinical partnerships","Education operations","Executive governance"],summary:"Decision support across the medical school–health-system boundary through UMCNO executive advisory work, CLER readiness, affiliate strategy, teaching-site relationships, and recurring integration with LCMC, OLOL, Ochsner and VA partners.",evidence:["ev-umcno-academic-advisory","ev-acgme-cler-umcno","ev-gme-lcmc-partner","ev-gme-olol-partner","ev-gme-ochsner-partner","ev-gme-va-partner"]},
    {num:"07",title:"GME Finance, Contracts & Workforce Strategy",domain:"Academic health-system operations",mandates:["Finance","Contracts","Workforce","Operational strategy"],summary:"Integrates Medicare and Medicaid GME policy, caps, FTEs, cost reports, DSH, affiliation agreements, partner negotiations, program growth, public-private hospital transition and workforce strategy into leadership-ready decision support.",evidence:["ev-gme-contracts-enterprise","ev-cms-cost-reports","ev-la-gme-cap","ev-state-medicaid-gme-liaison","ev-state-gme-medicaid-dsh","ev-ppp-hospital-transition","ev-lake-charles-lppf"]},
    {num:"08",title:"Assessment, Surveys & Outcomes Intelligence",domain:"Assessment & evaluation",mandates:["Surveys","Assessment","Outcomes","Organizational learning"],summary:"A longitudinal assessment practice spanning resident/fellow surveys, learner outcomes, admissions predictors, CME effectiveness, faculty-development evaluation, student research outcomes and leadership reporting—designed to convert assessment into program improvement and strategic decisions.",evidence:["ev-acgme-ape-surveys","ev-education-outcomes","ev-cme-activity","ev-faculty-development-eval","ev-medstudent-research-eval","ev-mcat-transition"]},
    {num:"09",title:"Enterprise AI Strategy, Governance & Responsible Adoption",domain:"AI & digital strategy",mandates:["AI strategy","Governance","Risk management","Responsible adoption"],summary:"AI governance extending from School of Medicine policy architecture to student and GME policy, cross-school consultation, LSU System governance participation, Cancer Center advisory work, faculty literacy, tool vetting and partner-governed clinical boundaries.",evidence:["ai-01","ev-ai-student-policy","ev-ai-gme-policy","ev-ai-cross-school","ev-ai-system","ev-cancer-ai-governance","ai-11"]},
    {num:"10",title:"Dean’s Office Special Projects & Executive Decision Support",domain:"Executive special projects",mandates:["Special projects","Executive advising","Benchmarking","Readiness"],summary:"A portfolio of high-stakes, time-bounded institutional projects for senior leadership: research growth benchmarking, federal AI/NCI readiness, facilities and space planning, healthcare-market analysis, enterprise technology due diligence, funding verification and strategic opportunity assessment.",evidence:["ev-nih-comparative","ev-federal-ai-nci","ev-cals-space","ev-market-charity","ev-watermark","ev-department-funding-verification"]},
    {num:"11",title:"Program Creation & Quality Improvement Infrastructure",domain:"Quality improvement & implementation",mandates:["Program development","QI","Metrics","Implementation"],summary:"Creation and operationalization of durable improvement infrastructure—from EQuIP’s GME quality framework to MCIP governance, informatics, education and the CALS evaluation architecture—linking structure, metrics, data collection, monitoring and implementation.",evidence:["ev-equip-creation","ev-mcip-governance","ev-mcip-gme","ev-mcip-cancer-learning","ev-cals-evaluation-framework","ev-gnochc-dashboard"]},
    {num:"12",title:"Admissions & Medical Education Strategy",domain:"Education strategy",mandates:["Admissions","Learner outcomes","Program evaluation","Innovation"],summary:"Admissions technology transformation, MCAT and predictor research, student-outcome intelligence, match reporting, clinical-rotation optimization and longitudinal medical-education analytics translated into policy, selection and program-improvement decisions.",evidence:["adm-01","ev-mcat-transition","ev-mcat-preclinical","ev-childrens-matching","ev-dean-match","ev-education-outcomes"]},
    {num:"13",title:"Research Growth, Cancer Strategy & NCI Readiness",domain:"Research strategy",mandates:["Research strategy","Benchmarking","Cancer strategy","Institutional growth"],summary:"NIH portfolio intelligence, clustering and peer benchmarking, research-enterprise integration, federal infrastructure reporting, training-grant support, Cancer Center governance and NCI-aligned readiness translated into institutional growth strategy.",evidence:["res-01","ev-nih-comparative","ev-huron","ev-research-office-integration","ev-nih-mdphd","ev-nsf-facilities","ev-federal-ai-nci"]},
    {num:"14",title:"Louisiana Health Workforce, Public Policy & Rural Strategy",domain:"Public-sector strategy",mandates:["Workforce","Public policy","Rural health","External stakeholders"],summary:"Longitudinal state-facing work across the Medical Education Commission, Healthworks Commission, LDH Bureau of Primary Care & Rural Health, physician workforce intelligence, HPSA/MUA infrastructure, legislative analysis, rural health strategy and GME financing.",evidence:["ev-mec","ev-healthworks","ev-ldh-primary-care","ev-lsbme-workforce","ev-la-med-ed-workforce","ev-rural-predictive","ev-health-welfare"]},
    {num:"15",title:"Faculty Affairs, Culture & Organizational Effectiveness",domain:"Faculty & organizational effectiveness",mandates:["Faculty lifecycle","Culture","Evaluation","Workforce"],summary:"Faculty-development evaluation, mentoring infrastructure, recruitment/retention analytics, promotion and compensation analysis, workforce reporting, teaching assessment, culture/equity intelligence and faculty-data governance across the academic lifecycle.",evidence:["fac-01","ev-faculty-development-eval","ev-faculty-salary","ev-faculty-workforce","ev-faculty-lifecycle","ev-teaching-assessment","ev-faculty-data-governance"]},
    {num:"16",title:"Enterprise Technology, Vendor & Data Governance",domain:"Digital transformation",mandates:["Technology governance","Vendor risk","Security","Data stewardship"],summary:"Enterprise technology governance beyond AI: admissions-platform transformation, Watermark Faculty Success due diligence, requirements definition, security/compliance review, vendor risk, legal and contract review, and data-governance implications.",evidence:["ev-watermark","adm-01","ev-faculty-data-governance","ev-ai-hiring-amc","ev-ai-hiring-cme"]},
    {num:"17",title:"International Partnerships & External Collaboration",domain:"Partnership development",mandates:["Partnerships","External engagement","International strategy","Relationship building"],summary:"Government-to-university and cross-institutional partnership development spanning India’s Ministry of Education, Study in India, IIT Madras, international simulation-science collaborations, and external academic/health-policy consultation.",evidence:["ev-india-moe-host","ev-study-in-india","res-07","ev-debriefing","ev-serf-collaboration","ev-external-consulting"]},
    {num:"18",title:"Governed Innovation & Clinical AI Prototyping",domain:"Future-focused innovation",mandates:["Innovation","Clinical AI","Safety","Human oversight"],summary:"Applied innovation built around governance rather than novelty alone: a pan-oncology multi-agent research prototype using provenance, independent evidence channels, missing-information gates, red-teaming, abstention, human attestation and auditability.",evidence:["ev-pan-oncology","ev-cancer-ai-governance","ev-ai-architecture-faculty","ev-fda-rfi"]}
  ];

  function artifact(id){ return (window.ARTIFACTS||[]).find(a=>a&&a.id===id); }
  function EvidenceChip({id,openArtifact}){ const a=artifact(id); if(!a) return null; return <button className="evidence-chip" onClick={()=>openArtifact&&openArtifact(a)}>{a.title}</button>; }
  function Mandates({items}){ return <div className="caso-mandates">{items.map(x=><span key={x}>{x}</span>)}</div>; }

  function ExecutiveHome({openArtifact}){
    const total=(window.ARTIFACTS||[]).length;
    const featured=CASES.slice(0,6);
    const systems=[
      ["01","Strategy implementation","Plans → priorities → KPIs → implementation → annual review."],
      ["02","Institutional effectiveness","Data governance, assessment, dashboards and organizational learning."],
      ["03","Accreditation & CQI","Continuous readiness, self-study, regulatory surveillance and corrective action."],
      ["04","Enterprise integration","Medical school, health-system, state and cross-school partnership governance."],
      ["05","AI & digital governance","Responsible adoption, policy, vendor risk and emerging-technology strategy."],
      ["06","Executive special projects","High-impact Dean’s Office work requiring evidence, coordination and execution."]
    ];
    return <main className="premium-home">
      <section className="premium-review-banner"><div className="container"><strong>Premium clone · review environment</strong><span>Original live portfolio preserved unchanged on main.</span></div></section>
      <section className="premium-hero"><div className="container premium-hero-grid"><div><div className="premium-kicker">Academic medicine · strategy · accreditation · institutional effectiveness</div><h1>Turning institutional priorities into governed execution.</h1><p className="premium-lede">A career-spanning practice at the intersection of strategic planning, accreditation, institutional effectiveness, data governance, academic health-system integration, AI strategy, public policy, and executive decision support.</p><div className="premium-hero-actions"><a href="#/case-studies" className="premium-primary">Explore executive cases</a><a href="#/library" className="premium-secondary">Search the evidence library</a></div></div><aside className="premium-hero-panel"><div className="panel-label">Executive operating model</div><div className="evidence-flow"><span>Strategy</span><b>→</b><span>Evidence</span><b>→</b><span>Governance</span><b>→</b><span>Execution</span></div><p>Selective executive cases synthesize the work; the full evidence library preserves the breadth and depth behind every claim.</p></aside></div></section>
      <section className="premium-stats"><div className="container premium-stat-grid"><div className="premium-stat"><strong>{total}</strong><span>evidence records</span><small>preservation-first career register</small></div><div className="premium-stat"><strong>18</strong><span>executive cases</span><small>curated around institutional leadership mandates</small></div><div className="premium-stat"><strong>90+</strong><span>institutional data sources</span><small>education · finance · research · workforce</small></div><div className="premium-stat"><strong>2007–</strong><span>LSU institutional experience</span><small>medical education → enterprise strategy</small></div></div></section>
      <section className="premium-pillars"><div className="container"><div className="section-head"><div><span className="premium-kicker">Executive mandate</span><h2>Six systems that make strategy executable.</h2></div><p>Organized around the operating responsibilities of a senior accreditation, strategy and institutional-effectiveness leader—not around a single employer’s terminology.</p></div><div className="pillar-grid">{systems.map(p=><article className="pillar-card" key={p[0]}><span>{p[0]}</span><h3>{p[1]}</h3><p>{p[2]}</p></article>)}</div></div></section>
      <section className="premium-featured"><div className="container"><div className="section-head"><div><span className="premium-kicker">Priority executive cases</span><h2>The strongest evidence for enterprise-level strategy leadership.</h2></div><a href="#/case-studies">View all 18 →</a></div><div className="featured-grid">{featured.map(c=><article className="featured-case" key={c.num}><div className="case-num">{c.num}</div><div className="case-domain">{c.domain}</div><h3>{c.title}</h3><Mandates items={c.mandates}/><p>{c.summary}</p><div className="case-evidence-row">{c.evidence.slice(0,2).map(id=><EvidenceChip key={id} id={id} openArtifact={openArtifact}/>)}</div></article>)}</div></div></section>
    </main>;
  }

  function ExecutiveCases({openArtifact}){
    return <main className="premium-page"><section className="premium-page-hero"><div className="container"><span className="premium-kicker">Executive case studies</span><h1>Institutional leadership through strategy, evidence, governance and execution.</h1><p>The first ten cases map directly to the core operating mandate of a senior accreditation and strategy executive: strategic-plan implementation, institutional effectiveness, data governance, accreditation, CQI, enterprise integration, AI strategy, cross-functional leadership, assessment and high-impact executive projects. The remaining cases demonstrate breadth in research, public policy, faculty affairs, technology, partnerships and governed innovation.</p></div></section><section className="container caso-case-groups"><div className="caso-group-head"><span>Core executive mandate</span><h2>01–10 · Strategy, accreditation, institutional effectiveness and enterprise leadership</h2></div><div className="premium-case-list">{CASES.slice(0,10).map(c=><CaseRow key={c.num} c={c} openArtifact={openArtifact}/>)}</div><div className="caso-group-head secondary"><span>Depth & breadth</span><h2>11–18 · Program creation, education, research, policy, faculty, technology and innovation</h2></div><div className="premium-case-list">{CASES.slice(10).map(c=><CaseRow key={c.num} c={c} openArtifact={openArtifact}/>)}</div></section></main>;
  }
  function CaseRow({c,openArtifact}){ const available=c.evidence.filter(id=>artifact(id)); return <article className="premium-case-row"><div className="case-index">{c.num}</div><div className="case-copy"><div className="case-domain">{c.domain}</div><h2>{c.title}</h2><Mandates items={c.mandates}/><p>{c.summary}</p><details><summary>{available.length} supporting evidence records</summary><div className="case-evidence-row expanded">{available.map(id=><EvidenceChip key={id} id={id} openArtifact={openArtifact}/>)}</div></details></div></article>; }

  const CAPABILITIES=[
    ["Strategic Planning & Implementation","Own the operating cycle from environmental analysis and stakeholder engagement through priorities, KPIs, implementation monitoring, annual review and strategic refresh.",["01","10"]],
    ["Institutional Effectiveness & Data Governance","Build evidence systems that connect data stewardship, assessment, dashboards, accreditation, CQI and mission outcomes across units.",["02","08"]],
    ["Accreditation & Continuous Readiness","Translate standards into evidence architecture, self-study readiness, monitoring, risk surveillance, corrective action and institutional learning.",["03","04"]],
    ["Enterprise Integration & Matrix Leadership","Lead across schools, academic health-system partners, committees, finance, contracts, IT, faculty and external stakeholders without relying on direct-line authority.",["05","06"]],
    ["Academic Health-System Operations","Integrate GME finance, contracts, workforce, training-site strategy, Medicaid/Medicare policy and clinical-learning-environment needs.",["06","07"]],
    ["AI & Digital Governance","Assess emerging technologies, create policy and governance, manage vendor and data risk, and support responsible adoption aligned with institutional mission.",["09","16","18"]],
    ["Executive Decision Support & Special Projects","Frame ambiguous problems, assemble evidence, benchmark externally, coordinate stakeholders, surface risks and deliver leadership-ready decision architecture.",["10","13","14"]],
    ["Assessment, Program Evaluation & Organizational Learning","Connect surveys, learner outcomes, faculty/program evaluation and quality metrics to decisions, remediation, strategy and continuous improvement.",["08","11","15"]]
  ];
  function ExecutiveCapabilities(){ return <main className="premium-page"><section className="premium-page-hero"><div className="container"><span className="premium-kicker">Executive capabilities</span><h1>Eight capabilities for institutional strategy and accreditation leadership.</h1><p>These capabilities are derived from the underlying work and evidence—not asserted as generic leadership traits.</p></div></section><section className="container caso-cap-grid">{CAPABILITIES.map((x,i)=><article className="caso-cap" key={x[0]}><span>{String(i+1).padStart(2,"0")}</span><h2>{x[0]}</h2><p>{x[1]}</p><div className="caso-related">Cases {x[2].join(" · ")}</div></article>)}</section></main>; }

  function ExecutiveAbout(){ return <main className="premium-page"><section className="premium-page-hero"><div className="container"><span className="premium-kicker">Professional profile</span><h1>Academic medical center institutional strategy and governance leader.</h1><p>Ram Paragi, MBBS, MPH, brings a career arc from clinical medicine and public health into medical-education research, accreditation, CQI, strategic planning, institutional effectiveness, GME finance, workforce policy, research intelligence and AI governance.</p></div></section><section className="container caso-about"><article><h2>Operating at the institutional interface</h2><p>Since joining LSU Health New Orleans in 2007, the work has increasingly centered on problems that cut across organizational boundaries: accreditation evidence, schoolwide strategic planning, educational outcomes, hospital partnerships, GME finance, state workforce policy, faculty analytics, research strategy and emerging technology governance.</p><p>The leadership model is matrixed. No direct-report supervision is claimed. Influence is exercised through process ownership, evidence architecture, governance structures, executive advising, cross-functional coordination and durable decision-support systems.</p></article><article><h2>What the portfolio demonstrates</h2><p>Depth in LCME and ACGME environments; major contribution to successful accreditation/reaccreditation work across LCME, ACGME and ACCME; institutional accreditation data-response experience through SACSCOC; strategy implementation; data governance; assessment and CQI; academic health-system operations; public policy; and responsible AI adoption.</p><p>The portfolio does not claim WSCUC Accreditation Liaison Officer experience or BPPE experience. Those remain explicit transferability gaps rather than being blurred into adjacent accreditation work.</p></article><article><h2>Decision architecture as a through-line</h2><p>Across domains, the recurring contribution is turning fragmented educational, regulatory, financial, workforce, research and policy data into a structure leaders can use: what is happening, why it matters, what risk is emerging, what decision is required, and how progress will be monitored.</p></article></section></main>; }

  window.HomePage=ExecutiveHome;
  window.CaseStudiesPage=ExecutiveCases;
  window.CapabilitiesPage=ExecutiveCapabilities;
  window.AboutPage=ExecutiveAbout;
  window.PREMIUM_EXECUTIVE_CASES=CASES;
})();